#!/bin/bash
set -euo pipefail

cd ${ZZIBOT_HOME}

git pull

docker build -t zzibot-app .

if docker ps -a --format '{{.Names}}' | grep -q '^zzibot$'; then
  docker rm zzibot --force
fi

docker run -d --name zzibot -p 8080:8080 zzibot-app
